<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col">

        <a class="footer-brand" href="/">LOGO</a>

        <address class="footer-address">
          <div itemscope itemtype="http://schema.org/PostalAddress">
              <span itemprop="name" class="sr-only">CLIENT NAME</span><br>
              <span itemprop="streetAddress">STREET ADDRESS</span><br>
              <span itemprop="addressLocality">CITY</span>,&nbsp;
              <span itemprop="addressRegion">STATE</span>&nbsp;
              <span itemprop="postalCode">ZIP CODE</span><br>
              <span itemprop="addressCountry">United States</span>
          </div>
        </address>

        <div itemscope itemtype="http://schema.org/Organization">
          <link itemprop="url" href="<%=PortalSettings.PortalAlias.HTTPAlias%>">
          <a itemprop="sameAs" href="#" class="">
            Facebook
          </a>
          <a itemprop="sameAs" href="#" class="">
            Twitter
          </a>
          <a itemprop="sameAs" href="#" class="">
            YouTube
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>
