<header class="header  fixed-to-top">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">

    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="/">LOGO</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <dnn:MENU runat="server" MenuStyle="menus/nav-primary" IncludeNodes=""></dnn:MENU>
      <div class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </div>
    </div>
  </nav>
</header>
